version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    steps:
      - checkout
      - run:
          name: Update it!
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]
            then
              curl -X PUT https://forums.bigbears.io/posts/6 -d api_key="$FORUM_API_KEY" --data-urlencode "post[raw]@README.md"
            fi
